language: python
python:
  - "3.7"
env:
  - ORT_RELEASE=${TRAVIS_BUILD_DIR}/onnxruntime_dist_cpu VENV_PATH='' PYTEST_ARGS="--cov=daceml --cov-report=term --cov-report xml --cov-config=.coveragerc -m 'not slow'"
install:
  - wget https://github.com/orausch/onnxruntime/releases/download/build1/onnxruntime_dist_cpu.tar.gz
  - tar -xzf onnxruntime_dist_cpu.tar.gz
  - make install
script:
  # test_models takes quite long, so we wait for up to 30 minutes
  - travis_wait 30 make test
  - make doctest
  - make codecov
  - make check-formatting
